### ISSUE TITLE
[BUG] - Duplicate imports for concrete collection types (e.g., HashMap) cause compilation errors in generated Kotlin entities

### ISSUE THREAD

**Issue by EmptyDreams** [babyfish-ct/jimmer#1307]
### Jimmer Version

0.9.119

### JDK Version

jdk21

### Database

MySQL

### OS

Mac

### Expected behavior

When generating implementation classes for Kotlin entities, Jimmer should import each type only once, using the appropriate fully qualified name that matches the declared property type. For a property declared as `HashMap<K, V>`, the generated code should import **either** `java.util.HashMap` **or** `kotlin.collections.HashMap`—whichever is consistent with Kotlin’s standard resolution—but **not both**.

### Actual behavior

For `@Serialized` properties of type `HashMap<K, V>`, the generated implementation class includes **two conflicting imports**:

```kotlin
import java.util.HashMap
import kotlin.collections.HashMap
```

This causes a compilation error:  
> "Cannot access 'HashMap': it is ambiguous which 'HashMap' is being referred to."

### Description

I defined a Kotlin entity interface with `@Serialized` properties using concrete collection types such as `HashMap<String, Int>`. Jimmer correctly preserves these types in the generated implementation class. However, the generated file contains **duplicate imports**—for example, both `import java.util.HashMap` and `import kotlin.collections.HashMap`—which leads to an ambiguous reference and a compilation error.

### Reproduction steps

1. Create a Kotlin entity interface with `@Serialized` properties:

   ```kotlin
   @Entity
   interface EntityA {
       @Serialized
       val a: ArrayList<Int>
       @Serialized
       val b: HashSet<Int>
       @Serialized
       val c: HashMap<Int, Int>
   }
   ```

2. Build the project.

3. Observe the generated implementation class for `EntityA`.

4. Notice that the generated file contains duplicate imports, for example:

   ```kotlin
   import java.util.ArrayList
   import kotlin.collections.ArrayList
   import java.util.HashSet
   import kotlin.collections.HashSet
   import java.util.HashMap
   import kotlin.collections.HashMap
   ```

This issue occurs consistently whenever a `@Serialized` property uses a concrete collection type that exists in both `java.util` and `kotlin.collections`.

**Comment by babyfish-ct** [comment]
This is a bug, it will be fixed.

However, this is bad practice, please use Collection interfaces such as `List, Set, Map`, rather than implementation classes.

**Comment by babyfish-ct** [comment]
Try `0.9.120`.

This behavior is forbidden *(it looks like bug of kotlinpoet)*, user must use the collection interface, rather than implementation class. Otherwise, compilation error will be reported.
